import type { AppState, BookCopy } from './types';
import { DEMO_INVITATION } from './demoInvitation';

const DAY = 24 * 60 * 60 * 1000;

function isoFrom(now: Date, offsetDays: number) {
  return new Date(now.getTime() + offsetDays * DAY).toISOString();
}

export function goodreadsSearchUrl(title: string, author = '') {
  return `https://www.goodreads.com/search?q=${encodeURIComponent(`${title} ${author}`.trim())}`;
}

export function createDemoState(now = new Date()): AppState {
  const books: BookCopy[] = [
    {
      id: 'book-wild-robot',
      title: 'The Wild Robot',
      author: 'Peter Brown',
      description: 'A warm adventure about a robot learning to survive—and belong—on a wild island.',
      ownerFamilyId: 'family-kapoor',
      ownerName: 'Kapoor family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Good',
      available: true,
      isbn: '9780316381994',
      seriesName: 'The Wild Robot',
      seriesNumber: '1',
      coverEmoji: '🤖',
      coverStyle: 'mint-sky',
      goodreadsUrl: goodreadsSearchUrl('The Wild Robot', 'Peter Brown'),
      createdAt: isoFrom(now, -12),
    },
    {
      id: 'book-wild-robot-mehta',
      title: 'The Wild Robot',
      author: 'Peter Brown',
      description: 'A warm adventure about a robot learning to survive—and belong—on a wild island.',
      ownerFamilyId: 'family-mehta',
      ownerName: 'Mehta family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Like new',
      available: true,
      isbn: '9780316381994',
      seriesName: 'The Wild Robot',
      seriesNumber: '1',
      coverEmoji: '🤖',
      coverStyle: 'blue-gold',
      goodreadsUrl: goodreadsSearchUrl('The Wild Robot', 'Peter Brown'),
      createdAt: isoFrom(now, -9),
    },
    {
      id: 'book-wild-robot-nair',
      title: 'The Wild Robot',
      author: 'Peter Brown',
      description: 'A warm adventure about a robot learning to survive—and belong—on a wild island.',
      ownerFamilyId: 'family-nair',
      ownerName: 'Nair family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Well loved',
      available: false,
      isbn: '9780316381994',
      seriesName: 'The Wild Robot',
      seriesNumber: '1',
      coverEmoji: '🤖',
      coverStyle: 'mint-sky',
      goodreadsUrl: goodreadsSearchUrl('The Wild Robot', 'Peter Brown'),
      createdAt: isoFrom(now, -7),
    },
    {
      id: 'book-geronimo',
      title: 'Lost Treasure of the Emerald Eye',
      author: 'Geronimo Stilton',
      description: 'A fast, funny treasure hunt filled with maps, mishaps and mouse-sized adventure.',
      ownerFamilyId: 'family-ahuja',
      ownerName: 'Ahuja family',
      ageBand: '6–8',
      category: 'Early reader',
      language: 'English',
      condition: 'Well loved',
      available: true,
      seriesName: 'Geronimo Stilton',
      seriesNumber: '1',
      coverEmoji: '🧀',
      coverStyle: 'lime-yellow',
      goodreadsUrl: goodreadsSearchUrl('Lost Treasure of the Emerald Eye', 'Geronimo Stilton'),
      createdAt: isoFrom(now, -8),
    },
    {
      id: 'book-gruffalo',
      title: 'The Gruffalo',
      author: 'Julia Donaldson',
      description: 'A clever little mouse takes a walk through the woods and invents a fearsome friend.',
      ownerFamilyId: 'family-bedi',
      ownerName: 'Bedi family',
      ageBand: '3–5',
      category: 'Picture book',
      language: 'English',
      condition: 'Good',
      available: true,
      coverEmoji: '🐭',
      coverStyle: 'peach-forest',
      goodreadsUrl: goodreadsSearchUrl('The Gruffalo', 'Julia Donaldson'),
      createdAt: isoFrom(now, -20),
    },
    {
      id: 'book-krishna',
      title: 'Krishna',
      author: 'Amar Chitra Katha',
      description: 'Illustrated stories from Indian mythology, retold for young readers.',
      ownerFamilyId: 'family-joshi',
      ownerName: 'Joshi family',
      ageBand: '6–8',
      category: 'Mythology',
      language: 'English',
      condition: 'Good',
      available: true,
      seriesName: 'Amar Chitra Katha',
      coverEmoji: '🪈',
      coverStyle: 'blue-gold',
      goodreadsUrl: goodreadsSearchUrl('Krishna Amar Chitra Katha'),
      createdAt: isoFrom(now, -30),
    },
    {
      id: 'book-matilda',
      title: 'Matilda',
      author: 'Roald Dahl',
      description: 'A brilliant young reader discovers courage, friendship and a rather unusual talent.',
      ownerFamilyId: 'family-aggarwal',
      ownerName: 'Aggarwal family',
      ageBand: '9–12',
      category: 'Chapter book',
      language: 'English',
      condition: 'Good',
      available: true,
      coverEmoji: '📚',
      coverStyle: 'pink-purple',
      goodreadsUrl: goodreadsSearchUrl('Matilda', 'Roald Dahl'),
      createdAt: isoFrom(now, -15),
    },
    {
      id: 'book-science',
      title: "A Child's Introduction to Science",
      author: 'Michael E. Bakich',
      description: 'A friendly illustrated introduction to space, physics, biology and the world around us.',
      ownerFamilyId: 'family-aggarwal',
      ownerName: 'Aggarwal family',
      ageBand: '9–12',
      category: 'Science & nature',
      language: 'English',
      condition: 'Like new',
      available: true,
      coverEmoji: '🔭',
      coverStyle: 'navy-coral',
      goodreadsUrl: goodreadsSearchUrl("A Child's Introduction to Science", 'Michael E. Bakich'),
      createdAt: isoFrom(now, -5),
    },
    {
      id: 'book-grandfather',
      title: "Grandfather's Bag of Stories",
      author: 'Sudha Murty',
      description: 'A collection of warm, wise stories told with humour and heart.',
      ownerFamilyId: 'family-aggarwal',
      ownerName: 'Aggarwal family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Well loved',
      available: true,
      coverEmoji: '🧳',
      coverStyle: 'amber-teal',
      goodreadsUrl: goodreadsSearchUrl("Grandfather's Bag of Stories", 'Sudha Murty'),
      createdAt: isoFrom(now, -21),
    },
    {
      id: 'book-dog-man',
      title: 'Dog Man',
      author: 'Dav Pilkey',
      description: 'A laugh-out-loud graphic adventure about a part-dog, part-man police hero.',
      ownerFamilyId: 'family-suri',
      ownerName: 'Suri family',
      ageBand: '6–8',
      category: 'Comic & graphic novel',
      language: 'English',
      condition: 'Good',
      available: true,
      seriesName: 'Dog Man',
      seriesNumber: '1',
      coverEmoji: '🐶',
      coverStyle: 'yellow-blue',
      goodreadsUrl: goodreadsSearchUrl('Dog Man', 'Dav Pilkey'),
      createdAt: isoFrom(now, -10),
    },
    {
      id: 'book-panchatantra',
      title: 'पंचतंत्र की कहानियाँ',
      author: 'Traditional tales',
      description: 'Colourful Hindi retellings of classic Panchatantra animal stories.',
      ownerFamilyId: 'family-chawla',
      ownerName: 'Chawla family',
      ageBand: '6–8',
      category: 'Early reader',
      language: 'Hindi',
      condition: 'Good',
      available: false,
      coverEmoji: '🦁',
      coverStyle: 'orange-plum',
      goodreadsUrl: goodreadsSearchUrl('Panchatantra Hindi stories'),
      createdAt: isoFrom(now, -3),
    },
    {
      id: 'book-history-charlottes-web',
      title: "Charlotte's Web",
      author: 'E. B. White',
      description: 'A classic story of friendship, loyalty and a very remarkable spider.',
      ownerFamilyId: 'family-kapoor',
      ownerName: 'Kapoor family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Good',
      available: true,
      coverEmoji: '🕸️',
      coverStyle: 'mint-sky',
      goodreadsUrl: goodreadsSearchUrl("Charlotte's Web", 'E. B. White'),
      createdAt: isoFrom(now, -120),
    },
    {
      id: 'book-history-malgudi-days',
      title: 'Malgudi Days',
      author: 'R. K. Narayan',
      description: 'Warm, memorable stories about everyday life in the fictional town of Malgudi.',
      ownerFamilyId: 'family-rao',
      ownerName: 'Rao family',
      ageBand: '9–12',
      category: 'Chapter book',
      language: 'English',
      condition: 'Well loved',
      available: true,
      coverEmoji: '🚂',
      coverStyle: 'amber-teal',
      goodreadsUrl: goodreadsSearchUrl('Malgudi Days', 'R. K. Narayan'),
      createdAt: isoFrom(now, -110),
    },
    {
      id: 'book-history-faraway-tree',
      title: 'The Magic Faraway Tree',
      author: 'Enid Blyton',
      description: 'Three children discover a magical tree filled with changing lands and adventures.',
      ownerFamilyId: 'family-sethi',
      ownerName: 'Sethi family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Good',
      available: true,
      seriesName: 'The Faraway Tree',
      seriesNumber: '2',
      coverEmoji: '🌳',
      coverStyle: 'lime-yellow',
      goodreadsUrl: goodreadsSearchUrl('The Magic Faraway Tree', 'Enid Blyton'),
      createdAt: isoFrom(now, -100),
    },
    {
      id: 'book-history-wrinkle',
      title: 'A Wrinkle in Time',
      author: "Madeleine L'Engle",
      description: 'A science-fantasy journey across space in search of a missing father.',
      ownerFamilyId: 'family-bose',
      ownerName: 'Bose family',
      ageBand: '9–12',
      category: 'Science & nature',
      language: 'English',
      condition: 'Like new',
      available: true,
      seriesName: 'Time Quintet',
      seriesNumber: '1',
      coverEmoji: '🌌',
      coverStyle: 'navy-coral',
      goodreadsUrl: goodreadsSearchUrl('A Wrinkle in Time', "Madeleine L'Engle"),
      createdAt: isoFrom(now, -90),
    },
    {
      id: 'book-history-blue-umbrella',
      title: 'The Blue Umbrella',
      author: 'Ruskin Bond',
      description: 'A gentle Himalayan story about desire, kindness and a beautiful blue umbrella.',
      ownerFamilyId: 'family-menon',
      ownerName: 'Menon family',
      ageBand: '6–8',
      category: 'Chapter book',
      language: 'English',
      condition: 'Good',
      available: true,
      coverEmoji: '☂️',
      coverStyle: 'blue-gold',
      goodreadsUrl: goodreadsSearchUrl('The Blue Umbrella', 'Ruskin Bond'),
      createdAt: isoFrom(now, -80),
    },
  ];

  return {
    version: 6,
    signedIn: false,
    family: {
      id: 'family-aggarwal',
      parentName: 'Arnaa Aggarwal',
      displayName: 'Aggarwal family',
      email: 'arnaa.aggarwal@example.test',
      whatsapp: '+91 90000 00000',
      successfulLoans: 5,
      onTimeLoans: 5,
    },
    community: {
      id: DEMO_INVITATION.circle.id,
      name: DEMO_INVITATION.circle.name,
      location: DEMO_INVITATION.circle.location,
      memberCount: 18,
      role: 'admin',
    },
    books,
    requests: [
      {
        id: 'request-gruffalo-first',
        bookId: 'book-gruffalo',
        borrowerFamilyId: 'family-bhatia',
        borrowerName: 'Bhatia family',
        requestedAt: isoFrom(now, -3),
        status: 'waiting',
      },
      {
        id: 'request-gruffalo-current',
        bookId: 'book-gruffalo',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        requestedAt: isoFrom(now, -2),
        status: 'waiting',
      },
      {
        id: 'request-matilda',
        bookId: 'book-matilda',
        borrowerFamilyId: 'family-malhotra',
        borrowerName: 'Malhotra family',
        requestedAt: isoFrom(now, -1),
        status: 'waiting',
      },
    ],
    loans: [
      {
        id: 'loan-krishna',
        bookId: 'book-krishna',
        lenderFamilyId: 'family-joshi',
        lenderName: 'Joshi family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'borrowed',
        acceptedAt: isoFrom(now, -6),
        handedOverAt: isoFrom(now, -5),
        receivedAt: isoFrom(now, -5),
        dueAt: isoFrom(now, 2),
      },
      {
        id: 'loan-grandfather',
        bookId: 'book-grandfather',
        lenderFamilyId: 'family-aggarwal',
        lenderName: 'Aggarwal family',
        borrowerFamilyId: 'family-malhotra',
        borrowerName: 'Malhotra family',
        status: 'return_pending',
        acceptedAt: isoFrom(now, -8),
        handedOverAt: isoFrom(now, -7),
        receivedAt: isoFrom(now, -7),
        dueAt: isoFrom(now, 0),
        borrowerMarkedReturnedAt: isoFrom(now, 0),
      },
      {
        id: 'loan-dog-man',
        bookId: 'book-dog-man',
        lenderFamilyId: 'family-suri',
        lenderName: 'Suri family',
        borrowerFamilyId: 'family-ahuja',
        borrowerName: 'Ahuja family',
        status: 'borrowed',
        acceptedAt: isoFrom(now, -4),
        handedOverAt: isoFrom(now, -3),
        receivedAt: isoFrom(now, -3),
        dueAt: isoFrom(now, 4),
      },
      {
        id: 'loan-history-charlottes-web',
        bookId: 'book-history-charlottes-web',
        lenderFamilyId: 'family-kapoor',
        lenderName: 'Kapoor family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'completed',
        acceptedAt: isoFrom(now, -105),
        handedOverAt: isoFrom(now, -104),
        receivedAt: isoFrom(now, -104),
        dueAt: isoFrom(now, -97),
        borrowerMarkedReturnedAt: isoFrom(now, -98),
        lenderConfirmedReturnedAt: isoFrom(now, -98),
      },
      {
        id: 'loan-history-malgudi-days',
        bookId: 'book-history-malgudi-days',
        lenderFamilyId: 'family-rao',
        lenderName: 'Rao family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'completed',
        acceptedAt: isoFrom(now, -84),
        handedOverAt: isoFrom(now, -83),
        receivedAt: isoFrom(now, -83),
        dueAt: isoFrom(now, -76),
        borrowerMarkedReturnedAt: isoFrom(now, -77),
        lenderConfirmedReturnedAt: isoFrom(now, -77),
      },
      {
        id: 'loan-history-faraway-tree',
        bookId: 'book-history-faraway-tree',
        lenderFamilyId: 'family-sethi',
        lenderName: 'Sethi family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'completed',
        acceptedAt: isoFrom(now, -63),
        handedOverAt: isoFrom(now, -62),
        receivedAt: isoFrom(now, -62),
        dueAt: isoFrom(now, -55),
        borrowerMarkedReturnedAt: isoFrom(now, -55),
        lenderConfirmedReturnedAt: isoFrom(now, -55),
      },
      {
        id: 'loan-history-wrinkle',
        bookId: 'book-history-wrinkle',
        lenderFamilyId: 'family-bose',
        lenderName: 'Bose family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'completed',
        acceptedAt: isoFrom(now, -42),
        handedOverAt: isoFrom(now, -41),
        receivedAt: isoFrom(now, -41),
        dueAt: isoFrom(now, -34),
        borrowerMarkedReturnedAt: isoFrom(now, -35),
        lenderConfirmedReturnedAt: isoFrom(now, -35),
      },
      {
        id: 'loan-history-blue-umbrella',
        bookId: 'book-history-blue-umbrella',
        lenderFamilyId: 'family-menon',
        lenderName: 'Menon family',
        borrowerFamilyId: 'family-aggarwal',
        borrowerName: 'Aggarwal family',
        status: 'completed',
        acceptedAt: isoFrom(now, -21),
        handedOverAt: isoFrom(now, -20),
        receivedAt: isoFrom(now, -20),
        dueAt: isoFrom(now, -13),
        borrowerMarkedReturnedAt: isoFrom(now, -14),
        lenderConfirmedReturnedAt: isoFrom(now, -14),
      },
    ],
    feedback: [],
    preferences: {
      shareWhatsappDuringHandover: true,
      emailReminders: true,
    },
    circleInvitations: [
      { id: 'invite-meera', recipientEmail: 'meera.sethi@example.test', code: 'GFC-MEERA7', createdAt: isoFrom(now, -1), expiresAt: isoFrom(now, 6), status: 'active' },
      { id: 'invite-arjun', recipientEmail: 'arjun.rao@example.test', code: 'GFC-ARJUN4', createdAt: isoFrom(now, -8), expiresAt: isoFrom(now, -1), status: 'redeemed' },
      { id: 'invite-neha', recipientEmail: 'neha.bose@example.test', code: 'GFC-NEHA2', createdAt: isoFrom(now, -5), expiresAt: isoFrom(now, 2), status: 'revoked' },
    ],
    circleMembers: [
      { id: 'family-aggarwal', parentName: 'Arnaa Aggarwal', familyName: 'Aggarwal family', email: 'arnaa.aggarwal@example.test', role: 'admin', status: 'active', joinedAt: isoFrom(now, -60), booksListed: 3, completedLoans: 5 },
      { id: 'family-kapoor', parentName: 'Rhea Kapoor', familyName: 'Kapoor family', email: 'rhea.kapoor@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -48), booksListed: 1, completedLoans: 4 },
      { id: 'family-ahuja', parentName: 'Nitin Ahuja', familyName: 'Ahuja family', email: 'nitin.ahuja@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -42), booksListed: 1, completedLoans: 3 },
      { id: 'family-malhotra', parentName: 'Simran Malhotra', familyName: 'Malhotra family', email: 'simran.malhotra@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -35), booksListed: 0, completedLoans: 2 },
      { id: 'family-bedi', parentName: 'Kabir Bedi', familyName: 'Bedi family', email: 'kabir.bedi@example.test', role: 'member', status: 'suspended', joinedAt: isoFrom(now, -29), booksListed: 1, completedLoans: 1 },
      { id: 'family-joshi', parentName: 'Maya Joshi', familyName: 'Joshi family', email: 'maya.joshi@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -27), booksListed: 1, completedLoans: 6 },
      { id: 'family-suri', parentName: 'Aman Suri', familyName: 'Suri family', email: 'aman.suri@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -25), booksListed: 1, completedLoans: 3 },
      { id: 'family-chawla', parentName: 'Tara Chawla', familyName: 'Chawla family', email: 'tara.chawla@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -24), booksListed: 1, completedLoans: 2 },
      { id: 'family-rao', parentName: 'Arjun Rao', familyName: 'Rao family', email: 'arjun.rao@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -22), booksListed: 1, completedLoans: 5 },
      { id: 'family-sethi', parentName: 'Meera Sethi', familyName: 'Sethi family', email: 'meera.sethi@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -20), booksListed: 1, completedLoans: 4 },
      { id: 'family-bose', parentName: 'Neha Bose', familyName: 'Bose family', email: 'neha.bose@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -18), booksListed: 1, completedLoans: 3 },
      { id: 'family-bhatia', parentName: 'Rohan Bhatia', familyName: 'Bhatia family', email: 'rohan.bhatia@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -16), booksListed: 0, completedLoans: 1 },
      { id: 'family-menon', parentName: 'Vikram Menon', familyName: 'Menon family', email: 'vikram.menon@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -14), booksListed: 1, completedLoans: 2 },
      { id: 'family-mehta', parentName: 'Ishita Mehta', familyName: 'Mehta family', email: 'ishita.mehta@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -12), booksListed: 1, completedLoans: 1 },
      { id: 'family-verma', parentName: 'Kunal Verma', familyName: 'Verma family', email: 'kunal.verma@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -10), booksListed: 0, completedLoans: 0 },
      { id: 'family-khanna', parentName: 'Dia Khanna', familyName: 'Khanna family', email: 'dia.khanna@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -8), booksListed: 0, completedLoans: 0 },
      { id: 'family-nair', parentName: 'Rahul Nair', familyName: 'Nair family', email: 'rahul.nair@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -6), booksListed: 1, completedLoans: 0 },
      { id: 'family-gupta', parentName: 'Sonal Gupta', familyName: 'Gupta family', email: 'sonal.gupta@example.test', role: 'member', status: 'active', joinedAt: isoFrom(now, -4), booksListed: 0, completedLoans: 0 },
    ],
    circleJoinRequests: [
      { id: 'join-varma', parentName: 'Ananya Varma', familyName: 'Varma family', email: 'ananya.varma@example.test', connectionNote: 'Referred by the Kapoor family from the same school community.', requestedAt: isoFrom(now, -2), status: 'pending' },
      { id: 'join-dhawan', parentName: 'Vikram Dhawan', familyName: 'Dhawan family', email: 'vikram.dhawan@example.test', connectionNote: 'Parent of a primary-school student in Gurgaon seeking a verified circle.', requestedAt: isoFrom(now, -1), status: 'pending' },
    ],
  };
}
